sugarcube-2:
  macros:

    # start meter macros
    newmeter:
      container: true
      children:
        - colors
        - sizing
        - animation
        - label
    colors:
      parents:
        - newmeter
    sizing:
      parents:
        - newmeter
    animation:
      parents:
        - newmeter
    label:
      parents:
        - newmeter
    showmeter: {}
    updatemeter: {}
    # end meter macros

    # start speech box system
    character:
      name: character
      parameters:
        - string &+ string |+ string
    say:
      name: say
      container: true
      parameters:
        - string |+ string
    ### You'll have to add your own character macros for the characters you create with <<character>> or setup.addCharacter()!

    ### Use this format:
    ### characterName:
    ###   name: characterName
    ###   container: true

    ### (Optional) If you for some reason want a description in the mouse-over tooltip you can add one to your character like it's done above in the say and character definitions.
    
    # end speech box system

    # simple inventory macros
    item:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    consumable:
      container: true
      children: 
        - description
        - tags
        - unique
        - permanent
    
    description:
      parents:
        -item
        -consumable
        
    tags:
      parents:
        -item
        -consumable
        
    unique:
      parents:
        -item
        -consumable
        
    permanent:
      parents:
        -item
        -consumable
    
    newinv: {}
    
    pickup: {}
    drop: {}
    dropall: {}

    transfer: {}
    merge: {}
    unmerge: {}
    
    inv: {}
    take : {}
    give : {}
    
    # end simple inventory
    